### ISSUE TITLE
Beta? No. Alpha Preview at best

### ISSUE THREAD

**Issue by yochananmarqos** [nayash/smarter-launcher#1]
The concept sounds great, but opening the fist app should immediately add it to the homescreen. As other apps are opened, the algorithm should adapt from there. 

You can't label a proof of concept release as Beta. That normally means it went through and Alpha stage and should be feature complete.

**Comment by nayash** [comment]
1. The algorithm predicts by "comparing" the current launch vector with existing history vectors and chooses N items of those. When u launch fisrt app, your history is empty. So predicting same app makes no sense. Even in the paper authors filter out current launch app from predictions anyway.
2. Regarding the release tag -- since this isn't a real release, I had not paid much attention to tags or convention. I have marked it as not ready for production use(although I have been using it for a month). It was just for people to try out quickly instead of building project themselves. Ignore it. BTW how do u know I have not done a closed alpha already :)

**Comment by yochananmarqos** [comment]
Great response. Will not be using it with a developer that responds like that for their first user / issue. Later.
